import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { FaSearch, FaArrowRight } from "react-icons/fa";
import API_URL from "../config/api";

export default function BlogPage() {
  const [blogs, setBlogs] = useState([]); const [search, setSearch] = useState(""); const [category, setCategory] = useState("All"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { let active=true; (async()=>{try{const r=await fetch(`${API_URL}/blogs`); const type=r.headers.get("content-type")||""; if(!r.ok||!type.includes("application/json")) throw new Error("Blog API is unavailable"); const d=await r.json(); if(active)setBlogs(d.blogs||[]);}catch(e){if(active)setError(e.message);}finally{if(active)setLoading(false)}})(); return()=>{active=false};},[]);
  const categories=["All",...new Set(blogs.map(b=>b.category))];
  const filtered=useMemo(()=>blogs.filter(b=>{const q=search.toLowerCase(); return (category==="All"||b.category===category)&&`${b.title} ${b.excerpt} ${(b.tags||[]).join(" ")}`.toLowerCase().includes(q)}),[blogs,search,category]);
  const featured=blogs.find(b=>b.featured);
  return <main className="max-w-7xl mx-auto px-5 pt-28 md:pt-36 pb-24 min-h-screen">
    <span className="section-eyebrow">Knowledge & insights</span><h1 className="text-4xl md:text-6xl font-display font-bold mt-4">Developer <span className="text-gradient">Blog</span></h1><p className="text-[var(--text-secondary)] mt-5 max-w-2xl leading-relaxed">Practical notes on MERN stack development, API integration, AI applications, Python and lessons learned while building real projects.</p>
    {featured && <article className="glass-card mt-10 p-6 md:p-10 grid md:grid-cols-[1.4fr_.6fr] gap-8"><div><span className="text-xs text-emerald-400">FEATURED · {featured.category}</span><h2 className="text-2xl md:text-4xl font-bold mt-3">{featured.title}</h2><p className="text-[var(--text-secondary)] mt-4 leading-relaxed">{featured.excerpt}</p><Link to={`/blog/${featured.slug}`} className="inline-flex items-center gap-2 text-emerald-400 font-semibold mt-6">Read featured article <FaArrowRight size={12}/></Link></div><div className="rounded-2xl border border-emerald-400/10 bg-emerald-400/[0.04] p-6 flex flex-col justify-end"><p className="text-4xl font-bold text-gradient">{featured.readTime}</p><p className="text-sm text-[var(--text-secondary)] mt-2">Practical, focused reading for developers.</p></div></article>}
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 mt-12"><div className="relative w-full md:max-w-md"><FaSearch className="absolute left-4 top-1/2 -translate-y-1/2 text-[var(--text-muted)]"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search articles, topics or technologies..." className="w-full pl-11 pr-4 py-3 rounded-xl bg-white/[0.04] border border-white/10 outline-none focus:border-emerald-400/60"/></div><div className="flex flex-wrap gap-2">{categories.map(c=><button onClick={()=>setCategory(c)} key={c} className={`pill ${category===c?"!border-emerald-400/60 !text-emerald-300":""}`}>{c}</button>)}</div></div>
    {loading?<p className="mt-10 text-[var(--text-secondary)]">Loading articles...</p>:error?<div className="glass-card p-8 mt-10"><p className="text-red-300">{error}</p><p className="text-sm text-[var(--text-secondary)] mt-2">Start the backend and open the blog again.</p></div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-6 mt-10">{filtered.map(b=><article key={b.id} className="glass-card p-6 flex flex-col min-h-[330px]"><div className="flex justify-between text-xs text-emerald-400"><span>{b.category}</span><span>{b.readTime}</span></div><h2 className="text-xl font-bold mt-4">{b.title}</h2><p className="text-sm text-[var(--text-secondary)] mt-3 leading-relaxed flex-1">{b.excerpt}</p><div className="flex flex-wrap gap-2 mt-5">{(b.tags||[]).slice(0,4).map(t=><span key={t} className="pill !py-1 !px-2 text-xs">{t}</span>)}</div><Link className="inline-flex items-center gap-2 mt-6 text-emerald-400 font-semibold" to={`/blog/${b.slug}`}>Read article <FaArrowRight size={11}/></Link></article>)}</div>}
    {!loading&&!error&&!filtered.length&&<p className="mt-10 text-[var(--text-secondary)]">No articles match your search.</p>}
  </main>
}
